<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-05-12T12:27:43+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/Amsterdam',
    'api_keys' => [
        'google' => [
            'maps' => '',
        ],
    ],
];
