<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-04-07T23:50:13+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/Amsterdam',
];
