<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2018-04-07T23:49:13+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Eric',
        ],
    ],
];
